{{- if .Values.enabled }}
{{- range .Values.topics }}
---
apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: {{ .name | replace "." "-" }}
  labels: { app.kubernetes.io/part-of: storemesh }
spec:
  kafkaClusterRef:
    name: {{ $.Values.clusterName }}
  partitionCount: {{ .partitions }}
  replicas: {{ $.Values.replicas }}
  configs:
    cleanup.policy: compact,delete
    retention.ms: "604800000"
{{- end }}
{{- end }}
