apiVersion: v1
kind: Service
metadata:
  name: storemesh-inventory-service
spec:
  type: {{ .Values.service.type }}
  selector: {app.kubernetes.io/name: storemesh-inventory-service}
  ports:
    - {name: grpc, port: {{ .Values.service.port }}, targetPort: grpc}
    - {name: http, port: 8080, targetPort: http}
