{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: storemesh-product-service
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ required "externalSecrets.secretStoreRef.name is required" .Values.externalSecrets.secretStoreRef.name }}
    kind: {{ .Values.externalSecrets.secretStoreRef.kind }}
  target:
    name: {{ required "externalSecrets.targetName is required" .Values.externalSecrets.targetName }}
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ required "externalSecrets.remoteKey is required" .Values.externalSecrets.remoteKey | quote }}
{{- end }}
