replicaCount: 2
pdb:
  enabled: true
  minAvailable: 1
networkPolicy:
  enabled: true
  allowedIngressNamespaces:
    - storemesh-order-service
prometheusRule:
  enabled: false
  additionalLabels: {}
serviceMonitor:
  enabled: false
  interval: 30s
  scrapeTimeout: 10s
  additionalLabels: {}

image:
  repository: ghcr.io/sartim/storemesh-product-service
  tag: "0.1.1"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 50051

secrets:
  existingSecret: storemesh-product-service-secrets
externalSecrets:
  enabled: false
  secretStoreRef: {name: "", kind: ClusterSecretStore}
  remoteKey: ""
  targetName: ""

config:
  jwtIssuer: storemesh-product-service
  jwtAudience: storemesh-platform

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
