apiVersion: v1
kind: Service
metadata:
  name: {{ include "storemesh-bff.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "storemesh-bff.name" . }}
    app.kubernetes.io/part-of: storemesh
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "storemesh-bff.name" . }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
