replicaCount: 2

nameOverride: ""
fullnameOverride: ""

image:
  repository: ghcr.io/sartim/storemesh-frontend
  tag: "0.1.5"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: false
  className: nginx
  annotations: {}
  host: storemesh.example.com
  tls:
    enabled: false
    secretName: storemesh-frontend-tls

istio:
  enabled: true
  host: storemesh.local
  gatewayNamespace: istio-ingress

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
