{{- if .Values.prometheusRule.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: storemesh-order-service
  labels: {{- toYaml .Values.prometheusRule.additionalLabels | nindent 4 }}
spec:
  groups:
    - name: storemesh-order-service
      rules:
        - alert: StoreMeshOrderServiceUnavailable
          expr: kube_deployment_status_replicas_available{namespace="{{ .Release.Namespace }}",deployment="storemesh-order-service"} < 1
          for: 10m
          labels: {severity: critical}
          annotations: {summary: StoreMesh Order Service has no available replicas}
{{- end }}
