replicaCount: 2
pdb:
  enabled: true
  minAvailable: 1
networkPolicy:
  enabled: true
  allowedIngressNamespaces: []
image:
  repository: ghcr.io/sartim/storemesh-order-service
  tag: "0.2.0"
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 50051
secrets:
  existingSecret: storemesh-order-service-secrets
dependencies:
  productAddress: storemesh-product-service.storemesh-product-service.svc.cluster.local:50051
  inventoryAddress: storemesh-inventory-service.storemesh-inventory-service.svc.cluster.local:50051
resources:
  requests: {cpu: 100m, memory: 128Mi}
  limits: {cpu: 500m, memory: 512Mi}
